// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0ApVSXve8aslHqoSz6tKrt9uy3X0QeY',
    appId: '1:1044504479464:web:05c86537dc33834e9deb5d',
    messagingSenderId: '1044504479464',
    projectId: 'cfisher19-cmsc4303-lesson4',
    authDomain: 'cfisher19-cmsc4303-lesson4.firebaseapp.com',
    storageBucket: 'cfisher19-cmsc4303-lesson4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmxG6zJgpXXZERThelv3WE8-6BXniG1Q',
    appId: '1:1044504479464:android:0a34ce4300a6a6f89deb5d',
    messagingSenderId: '1044504479464',
    projectId: 'cfisher19-cmsc4303-lesson4',
    storageBucket: 'cfisher19-cmsc4303-lesson4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgO9MNGMgFslAQ93U_Kj1vZLkslyTN-Sc',
    appId: '1:1044504479464:ios:7d840de0c211375c9deb5d',
    messagingSenderId: '1044504479464',
    projectId: 'cfisher19-cmsc4303-lesson4',
    storageBucket: 'cfisher19-cmsc4303-lesson4.appspot.com',
    iosClientId: '1044504479464-nk0ugr6rd2qmb8hcbi0v07jojvtsp1h2.apps.googleusercontent.com',
    iosBundleId: 'edu.uco.cfisher19.project3',
  );
}
